/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JRadioButton;
import model.User;

/**
 *
 * @author Admin
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPanel
     */
    private User newUser;
    public ViewPanel(User newUser) {
        initComponents();
        this.newUser=newUser;
        populateData();
    }
    
    public void setUser(User user) {
        this.newUser = user;
        populateData();
    }

   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        patientTypeLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        firstNameDataLabel = new javax.swing.JLabel();
        lastNameDataLabel = new javax.swing.JLabel();
        messageDataLabel = new javax.swing.JLabel();
        emailDataLabel = new javax.swing.JLabel();
        dobDataLabel = new javax.swing.JLabel();
        ageDataLabel = new javax.swing.JLabel();
        imageDataLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        patientTypeDataLabel = new javax.swing.JLabel();
        genderDataLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        titleLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        titleLabel.setText("        View Patient Form");

        firstNameLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        firstNameLabel.setText("First Name");

        lastNameLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lastNameLabel.setText("Last Name");

        ageLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ageLabel.setText("Age");

        emailLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        emailLabel.setText("Email");

        messageLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        messageLabel.setText("Message");

        patientTypeLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        patientTypeLabel.setText("Patient Type");

        genderLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        genderLabel.setText("Gender");

        firstNameDataLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        lastNameDataLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        messageDataLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        emailDataLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        dobDataLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        ageDataLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        dobLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        dobLabel.setText("Date of Birth");

        patientTypeDataLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        genderDataLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel)
                    .addComponent(lastNameLabel)
                    .addComponent(emailLabel)
                    .addComponent(patientTypeLabel)
                    .addComponent(genderLabel)
                    .addComponent(messageLabel)
                    .addComponent(ageLabel)
                    .addComponent(dobLabel))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(patientTypeDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(messageDataLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailDataLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lastNameDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(firstNameDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dobDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ageDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addComponent(imageDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 43, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(firstNameLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lastNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(dobLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lastNameDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dobDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailLabel)
                            .addComponent(emailDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messageLabel)
                            .addComponent(messageDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientTypeLabel)
                            .addComponent(patientTypeDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderLabel)
                            .addComponent(genderDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firstNameDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(ageDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imageDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageDataLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel dobDataLabel;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel emailDataLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel firstNameDataLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel genderDataLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel imageDataLabel;
    private javax.swing.JLabel lastNameDataLabel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel messageDataLabel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel patientTypeDataLabel;
    private javax.swing.JLabel patientTypeLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    private void populateData() {
        firstNameDataLabel.setText(this.newUser.getFirstName()); //text field data
        lastNameDataLabel.setText(this.newUser.getLastName()); //text field data
        dobDataLabel.setText(this.newUser.getDob());
        ageDataLabel.setText(this.newUser.getAge());
        emailDataLabel.setText(this.newUser.getEmail());
        messageDataLabel.setText(this.newUser.getMessage()); 
        patientTypeDataLabel.setText(this.newUser.getPatientType()); // dropdown data
        genderDataLabel.setText(this.newUser.getGender());
        ImageIcon ii = new ImageIcon(this.newUser.getPath());
        Image image = ii.getImage().getScaledInstance(70,80, Image.SCALE_SMOOTH);
        imageDataLabel.setIcon(new ImageIcon(image));
    }
}
